services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ct
    ports:
      - "3306:3306"
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "smart_guidance"
    volumes:
      - mysql-data:/var/lib/mysql
      - /data/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:alpine
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-network
    volumes:
      - redis-data:/data
      - redis-logs:/logs:z
      - /data/redis/config:/usr/local/etc/redis:z
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "8500:80"
    networks:
      - my-network
    volumes:
      - /data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/html:/usr/share/nginx/html
      - /data/nginx/logs:/var/log/nginx
    depends_on:
      ruoyi-app:
        condition: service_healthy

  ruoyi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruoyi-app
    ports:
      - "8082:8082"
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smart_guidance?useSSL=false&characterEncoding=utf8
      SPRING_REDIS_HOST: redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 30s

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  redis-logs:
  redis-config:
